version: '2.1'

services:
  bar-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: docker.artifactory.reform.hmcts.net/bar/bar-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bar-database:5432/bar
      - SPRING_DATASOURCE_USERNAME=bar
      - SPRING_DATASOURCE_PASSWORD=bar
      - AUTH_IDAM_CLIENT_BASEURL=https://idam-test.dev.ccidam.reform.hmcts.net
    ports:
     - 8182:8080
    depends_on:
      bar-database:
        condition: service_healthy

  bar-database:
    build:
      context: docker/database
    image: docker.artifactory.reform.hmcts.net/bar-register/bar-database
    environment:
      - BAR_DB_USERNAME=bar
      - BAR_DB_PASSWORD=bar
    ports:
      - 5182:5432
