version: '2.1'

services:
  bar-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/hmcts/bar-api
    container_name: bar-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bar-database:5432/bar
      - SPRING_DATASOURCE_USERNAME=bar
      - SPRING_DATASOURCE_PASSWORD=bar
      - auth.idam.client.baseUrl=http://idam-api:5000
      - payment.api.url=http://payment-api-aat.service.core-compute-aat.internal
      - idam.s2s-auth.url=http://service-auth-provider-api:8489
      - idam.s2s-auth.microservice=bar_api
      - idam.s2s-auth.totp_secret=PKSFGXK7JA4UBTJV
      - site.api.url=http://bar-api:8080
    ports:
     - 8185:8080
    depends_on:
      - bar-database
      - service-auth-provider-api
      - idam-api
        
  service-auth-provider-api:
    image: hmctspublic.azurecr.io/rpe/service-auth-provider
    environment:
      - microserviceKeys_payment_app=AAAAAAAAAAAAAAAB
      - microserviceKeys_bar_api=PKSFGXK7JA4UBTJV
    ports:
      - 8085:8489

  bar-database:
    build:
      context: docker/database
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=bar
      - POSTGRES_PASSWORD=bar
      - POSTGRES_DB=bar
    ports:
      - 5182:5432
    volumes:
      - bar-database-data:/var/lib/postgresql/data

  fr-am:
    image: hmctsprivate.azurecr.io/idam/idam-fr-am:latest
    hostname: localam
    depends_on:
      - shared-db
    ports:
      - 8080:8080
      - 1389:1389

  fr-idm:
    image: hmctsprivate.azurecr.io/idam/idam-fr-idm:latest
    hostname: localidm
    depends_on:
      - fr-am
      - shared-db
    ports:
      - 18080:18080
      - 9010:9010
  shared-db:
    image: hmctsprivate.azurecr.io/idam/shared-db:latest
    ports:
      - 5432:5432
  smtp-server:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
  idam-api:
    image: hmctspublic.azurecr.io/idam/api:stable
    depends_on:
      - fr-am
      - shared-db
    ports:
      - 5000:5000
    tmpfs: /opt/app/es
    environment:
      - JAVA_OPTS=-Xms128m -Xms512m
      - IDAMHEALTHCHECK_AM_ENABLED=false
      - IDAMHEALTHCHECK_IDM_ENABLED=false
      - STRATEGIC_ADMIN_URL=http://idam-web-admin:8082
      - STRATEGIC_WEBPUBLIC_URL=http://idam-web-public:9002
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-db:5432/openidm?currentSchema=fridam
      - SPRING_DATASOURCE_USERNAME=openidm
      - SPRING_DATASOURCE_PASSWORD=openidm
      - SECURITY_OAUTH2_CLIENT_CLIENTSECRET=password
      - SECURITY_OAUTH2_CLIENT_PRE_ESTABLISHED_REDIRECT_URI=http://idam-web-public:9002/login
      - SECURITY_OAUTH2_CLIENT_REGISTERED_REDIRECT_URI=http://idam-web-public:9002/login
      - IDAM_SPI_FORGEROCK_AM_ROOT=http://fr-am:8080/openam
      - IDAM_SPI_FORGEROCK_AM_TOPLEVELHOST=fr-am
      - IDAM_SPI_FORGEROCK_AM_USERNAME=amadmin
      - IDAM_SPI_FORGEROCK_AM_PASSWORD=Pa55word11
      - IDAM_SPI_FORGEROCK_AM_JWKSURIFOROAUTH2CLIENTS=http://fr-am:8080/openam/oauth2/hmcts/connect/jwk_uri
      - IDAM_SPI_FORGEROCK_IDM_ROOT=http://fr-idm:18080/openidm
      - IDAM_SPI_FORGEROCK_IDM_USERNAME=openidm-admin
      - IDAM_SPI_FORGEROCK_IDM_PASSWORD=openidm-admin
      - IDAM_SPI_FORGEROCK_IDM_PIN_DEFAULTPASSWORD=BlaBlaBlackSh33p
      - APPSETTING_NODE_PATH=/opt/app
  idam-web-public:
    image: hmctspublic.azurecr.io/idam/web-public:stable
    depends_on:
      - idam-api
    ports:
      - 9002:8080
    environment:
      - JAVA_OPTS=-Xms128m -Xms512m
      - STRATEGIC_SERVICE_URL=http://idam-api:5000
  idam-web-admin:
    image: hmctspublic.azurecr.io/idam/web-admin:stable
    depends_on:
      - idam-api
    ports:
      - 8082:8080
    environment:
      - JAVA_OPTS=-Xms128m -Xms512m
      - STRATEGIC_SERVICE_URL=http://idam-api:5000
      - STRATEGIC_PUBLIC_URL=http://idam-web-public:9002

volumes:
  bar-database-data:
