java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    #SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-bar-db:5432/bar"
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: "{{ .Values.postgresql.auth.database}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.auth.username}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    POSTGRES_CONNECTION_OPTIONS: "?sslmode=allow"
    SPRING_LIQUIBASE_ENABLED: true
    postgresql:
      postgresqlUsername: bar
      postgresqlPassword: bar
      postgresqlDatabase: bar
  keyVaults:
    bar:
      secrets:
        - bar-S2S-SECRET
  postgresql:
    enabled: true
