java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  aadIdentityName:
  environment:
    #SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-bar-db:5432/bar"
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    POSTGRES_CONNECTION_OPTIONS: "?sslmode=allow"
    SPRING_LIQUIBASE_ENABLED: true
    SPRING_CLOUD_PROPERTIESVOLUME_ENABLED: false
  postgresql:
    postgresqlUsername: bar
    postgresqlPassword: bar
    postgresqlDatabase: bar
postgresql:
    enabled: true
