apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
data:
  PAYMENT_API_URL: "http://payment-api-aat.service.core-compute-aat.internal"
  S2S_AUTH_URL: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
  IDAM_CLIENT_BASE_URL: "https://preprod-idamapi.reform.hmcts.net:3511"
  SPRING_LIQUIBASE_ENABLED: "true"
