apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
data:
  LIQUIBASE_ENABLED = "true"
idam:
  IDAM_API_URL = "https://preprod-idamapi.reform.hmcts.net:3511"
